# -*- coding: utf-8 -*-
"""Descriptive_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZhpXYySye4Bkv1QmBCFs5okGXmw-z9S
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statistics

member_names=["Aman","Riya","Karan","Sneha","Rahul"]
ages=[22,25,24,23,26]
workout_hours=[2,1.5,2.5,1,3]
calories_burned=[500,350,600,300,750]
print("Fitness dataset loaded successfully")

average_workout=sum(workout_hours)/len(workout_hours)
print("Average workout hours:",average_workout)

highest_calories=max(calories_burned)
print("Highest calories burned:",highest_calories)

lowest_calories=min(calories_burned)
print("Lowest calories burned:",lowest_calories)

for i in range(len(member_names)):
  print("Member:",member_names[i])
  print("Age:",ages[i])
  print("Workout hours:",workout_hours[i])
  print("Calories burned:",calories_burned[i])

median_calories=np.median(calories_burned)
print("Median calories burned:",median_calories)

std_dev=statistics.stdev(calories_burned)
print("Standard deviation of calories burned:",std_dev)


index=calories_burned.index(highest_calories)
print("Most active member:",member_names[index])

index=calories_burned.index(lowest_calories)
print("Least active member:",member_names[index])

plt.bar(member_names,calories_burned)
plt.xlabel("Member Names")
plt.ylabel("calories_burned")
plt.title("calories burned")
plt.show()

plt.scatter(member_names,calories_burned)
plt.xlabel("Member Names")
plt.ylabel("calories_burned")
plt.title("calories burned")
plt.show()

plt.pie(ages,labels=member_names,autopct="%1.1f%%")
plt.title("Member Age Distribution")
plt.show()