# -*- coding: utf-8 -*-
"""Diagnostic_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fbbCk7wFYuooVX92UYWLrrN6iMAaw0t2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

data = {
    'CustomerID': range(1, 11),
    'Age': np.random.randint(18, 70, 10),
    'Gender': np.random.choice(['Male', 'Female'], 10),
    'ServiceType': np.random.choice(['Fiber Optic', 'DSL', 'No Internet'], 10),
    'MonthlyCharges': np.round(np.random.uniform(20, 150, 10), 2),
    'DataUsageGB': np.round(np.random.uniform(10, 500, 10), 2),
    'ContractType': np.random.choice(['Month-to-month', 'One year', 'Two year'], 10),
    'TotalSpent': np.round(np.random.uniform(50, 5000, 10), 2),
    'Churn': np.random.choice([0, 1], 10, p=[0.7, 0.3])
}
telecom_df = pd.DataFrame(data)

print("Sample Telecom Dataset:")
display(telecom_df)

#converting gender to 0&1
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
telecom_df['Gender'] = label_encoder.fit_transform(telecom_df['Gender'])
display(telecom_df)

print(telecom_df.info())

display(telecom_df.describe())

#internet speed
internet=telecom_df.groupby('ServiceType')['DataUsageGB'].mean().reset_index()
display(internet)

#payment failure
payment_failure=telecom_df.groupby('Churn')['TotalSpent'].mean().reset_index()
display(payment_failure)

#Deliver charges
deliver_charges=telecom_df.groupby('ContractType')['MonthlyCharges'].mean().reset_index()
display(deliver_charges)

#purchase completed
purchase_completed=telecom_df.groupby('Churn')['TotalSpent'].sum().reset_index()
display(purchase_completed)

#Total Abonded
total_abandoned=telecom_df.groupby('Churn')['TotalSpent'].count().reset_index()
display(total_abandoned)

#intenet diagnosis
internet=telecom_df.groupby('ServiceType')['Churn'].mean().reset_index()
display(internet)

#payment diagnosis
payment=telecom_df.groupby('Churn')['MonthlyCharges'].mean().reset_index()
display(payment)

#delivery Diagnosis
delivery=telecom_df.groupby('ContractType')['MonthlyCharges'].mean().reset_index()
display(delivery)

#find route cause
root_cause=telecom_df.groupby('Churn')['ServiceType'].value_counts().reset_index(name='Count')
display(root_cause)

#visualization
plt.figure(figsize=(10, 6))
plt.plot(internet['ServiceType'], internet['Churn'], color='blue')
plt.xlabel('Service Type')
plt.ylabel('Churn Rate')
plt.title('Churn Rate by Service Type')
plt.xticks(rotation=45)
plt.show()