# -*- coding: utf-8 -*-
"""e-commerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaSCH39XGdCMyBs69oUTzlxwwv0WGEg6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Ecommerce_Sales_Data_2024_2025 (1).csv', parse_dates=['Order Date'])
df.describe()

df.head()

#preprocessing
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Product Name']=le.fit_transform(df['Product Name'])
df.head()

# Check for missing values
print("Missing values per column:")
display(df.isnull().sum())

# Check for duplicate rows
print(f"Number of duplicate rows: {df.duplicated().sum()}")

# Check data types and non-null counts
print("Data types and non-null counts:")
df.info()

"""### Sales Trend Analysis"""

# Extract time-based features
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
df['Order DayOfWeek'] = df['Order Date'].dt.dayofweek # Monday=0, Sunday=6
df['Order MonthYear'] = df['Order Date'].dt.to_period('M')

display(df[['Order Date', 'Order Year', 'Order Month', 'Order DayOfWeek', 'Order MonthYear']].head())

"""#### Monthly Sales Trend"""

monthly_sales = df.groupby('Order MonthYear')['Sales'].sum().reset_index()
monthly_sales['Order MonthYear'] = monthly_sales['Order MonthYear'].astype(str)

plt.figure(figsize=(15, 6))
sns.lineplot(x='Order MonthYear', y='Sales', data=monthly_sales)
plt.title('Monthly Sales Trend (2024-2025)')
plt.xlabel('Month-Year')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""#### Sales by Category"""

sales_by_category = df.groupby('Category')['Sales'].sum().sort_values(ascending=False).reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(x='Category', y='Sales', data=sales_by_category, palette='viridis')
plt.title('Total Sales by Category')
plt.xlabel('Category')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""#### Sales by Region"""

sales_by_region = df.groupby('Region')['Sales'].sum().sort_values(ascending=False).reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(x='Region', y='Sales', data=sales_by_region, palette='magma')
plt.title('Total Sales by Region')
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.tight_layout()
plt.show()

"""#### Sales by Payment Mode"""

sales_by_payment_mode = df.groupby('Payment Mode')['Sales'].sum().sort_values(ascending=False).reset_index()

plt.figure(figsize=(10, 5))
sns.barplot(x='Payment Mode', y='Sales', data=sales_by_payment_mode, palette='cubehelix')
plt.title('Total Sales by Payment Mode')
plt.xlabel('Payment Mode')
plt.ylabel('Total Sales')
plt.tight_layout()
plt.show()

