# -*- coding: utf-8 -*-
"""Fitness_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15t1ezFb7r6QzZNXt1RLye1fJT9gFoYnm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#read csv file
df = pd.read_csv('/content/fitness_tracker.csv')
df.head()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled.head()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled.head()

#find max calories burned
df_scaled['Calories_Burned'].max()

df_scaled['Calories_Burned'].min()

#mean
df_scaled['Calories_Burned'].mean()

#most active person
max_calories_idx = df_scaled['Calories_Burned'].idxmax()
user_id_most_active = df.loc[max_calories_idx, 'User_ID']
print(f"The User ID with the most calories burned is: {user_id_most_active}")

#most lazy person
min_calories_idx = df_scaled['Calories_Burned'].idxmin()
user_id_most_lazy = df.loc[min_calories_idx, 'User_ID']
print(f"The User ID with the most calories burned is: {user_id_most_lazy}")

#standard devation
df_scaled['Calories_Burned'].std()

#variance
df_scaled['Calories_Burned'].var()

#line plot
df_scaled['Calories_Burned'].plot(kind='line')
plt.show()

plt.scatter(df_scaled['Calories_Burned'], df_scaled['Steps'])
plt.show()

