# -*- coding: utf-8 -*-
"""Predictive_Analytics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLV0n_wBMOhGMk2efW0b0nm1tUJ1zIpx
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from datetime import datetime, timedelta

# Set a random seed for reproducibility
np.random.seed(42)

# Generate a time series for one month
start_date = datetime(2023, 10, 1)
dates = [start_date + timedelta(hours=i) for i in range(24 * 30)] # 30 days, hourly data

# Generate synthetic data for water tank
water_level = np.random.uniform(20, 100, len(dates)) # Water level percentage
temperature = np.random.uniform(15, 30, len(dates)) # Water temperature in Celsius
ph_level = np.random.uniform(6.5, 8.5, len(dates)) # pH level
turbidity = np.random.uniform(0.5, 5, len(dates)) # Turbidity in NTU
pump_status = np.random.choice([0, 1], len(dates), p=[0.7, 0.3]) # 0 for off, 1 for on
flow_rate = np.random.uniform(0, 10, len(dates)) * pump_status # Flow rate in L/min, only if pump is on

# Introduce some trends and noise
water_level = water_level + np.sin(np.arange(len(dates)) / 24) * 10 # Daily fluctuation
temperature = temperature + np.sin(np.arange(len(dates)) / (24*7)) * 3 # Weekly fluctuation

# Ensure water level stays within 0-100
water_level = np.clip(water_level, 0, 100)

# Create DataFrame
water_tank_df = pd.DataFrame({
    'timestamp': dates,
    'water_level_percent': water_level,
    'temperature_celsius': temperature,
    'ph_level': ph_level,
    'turbidity_ntu': turbidity,
    'pump_status': pump_status,
    'flow_rate_L_min': flow_rate
})

# Display the first 5 rows of the dataset
display(water_tank_df.head())

print(water_tank_df.info())

#Water Consumption
Water_Consumption = water_tank_df['flow_rate_L_min'].sum()
days=len(water_tank_df)/24
Water_Consumption=Water_Consumption/days
print(Water_Consumption)

#Average Water Consumption
Average_Water_Consumption = water_tank_df['flow_rate_L_min'].mean()
print(Average_Water_Consumption)

#Total water usage in a day
Total_Water_Usage = water_tank_df['flow_rate_L_min'].sum()
print(Total_Water_Usage)

#Water usage increased
Water_Usage_Increased = water_tank_df['flow_rate_L_min'].max() - water_tank_df['flow_rate_L_min'].min()
print(Water_Usage_Increased)

#visualization
plt.bar(water_tank_df['timestamp'], water_tank_df['flow_rate_L_min'])
plt.xlabel('Timestamp')
plt.ylabel('Flow Rate (L/min)')
plt.title('Flow Rate Over Time')
plt.xticks(rotation=45)
plt.show()