# -*- coding: utf-8 -*-
"""Statistical Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M_zc4l7q2-j9p3fzxQ90HwtW9APciLzl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

marks=[40,50,55,65,75,45]
hours=[2,3,4,5,3,4]

print("Mean:",np.mean(marks))
print("Median:",np.median(marks))
print("Variance:",np.var(marks))
print("Standard Deviation:",np.std(marks))
print("Correlation:",np.corrcoef(marks,hours))

df=pd.DataFrame({'Marks':marks,'Hours':hours})
df.head()

plt.plot(marks,hours)
plt.show()